#ifndef LIBIEC61850_COMMON_API_FORWARDER_FROM_LOGGING_H_
#define LIBIEC61850_COMMON_API_FORWARDER_FROM_LOGGING_H_

#include "../common/inc/libiec61850_common_api.h"

#endif /* LIBIEC61850_COMMON_API_FORWARDER_FROM_LOGGING_H_ */

